# Generated by Django 4.2.3 on 2023-08-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CategoryName',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Category',
            new_name='category_listing',
        ),
    ]
