# Generated by Django 4.2.3 on 2023-08-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_alter_listing_price_delete_bidding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='by_user',
        ),
    ]
